
Vagrant.configure("2") do |config|

  config.vm.box = "puppetlabs/centos-7.2-64-nocm"

  config.vm.define "cassandra" do |cassandra|
    cassandra.vm.hostname = "cassandra"
    cassandra.vm.provision "shell", path: "scripts/boot.sh"
    cassandra.vm.provision "shell", path: "scripts/cassandra.sh"
    cassandra.vm.provision "shell", path: "scripts/nodejs.sh"
    cassandra.vm.network "private_network", ip: "10.0.0.11"
    cassandra.vm.network "forwarded_port", guest: 9042, host: 9042
  end

end
